/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./env.d.ts --include-runtime false` (hash: 6010a708c06bc23c7560fb010e7426bd)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Chat";
	}
	interface Env {
		Chat: DurableObjectNamespace /* Chat */;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
